package com.fusemachines.predict.game;

public enum Country {
	TURKEY, ITALY, WALES, SWITZERLAND,
	DENMARK, FINLAND, BELGIUM, RUSSIA,
	NETHERLANDS, UKRAINE, AUSTRIA, NORTH_MACEDONIA,
	ENGLAND, CROATIA, SCOTLAND, CZECH_REPUBLIC,
	SPAIN, SWEDEN, POLAND, SLOVAKIA,
	HUNGARY, PORTUGAL, FRANCE, GERMANY
}
