package com.fusemachines.predict.game;

public enum Country {
	EGYPT, MOROCCO, NIGERIA, SENEGAL, TUNISIA, AUSTRALIA, IRAN, JAPAN,
	KOREA, SAUDI_ARABIA, BELGIUM, CROATIA, DENMARK, ENGLAND, FRANCE, GERMANY,
	ICELAND, POLAND, PORTUGAL, RUSSIA, SERBIA, SPAIN, SWEDEN, SWITZERLAND,
	COSTA_RICA, MEXICO, PANAMA, ARGENTINA, BRAZIL, COLOMBIA, PERU, URUGUAY
}
